#!/bin/bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Build MSCCL++ from source for use with torchcomms.
# Supports NVIDIA (CUDA) and AMD (ROCm) platforms.
#
# Usage:
#   ./build_mscclpp.sh                    # Default: build for CUDA
#   ./build_mscclpp.sh --rocm             # Build for ROCm
#   ./build_mscclpp.sh --clean            # Clean rebuild
#   ./build_mscclpp.sh --tag v0.5.2       # Pin to a specific release
#
# After building:
#   export MSCCLPP_HOME=$PWD/third-party/mscclpp/install
#   USE_MSCCLPP=ON pip install --no-build-isolation -v .

set -euo pipefail

# --- Defaults ---
MSCCLPP_REPO="https://github.com/microsoft/mscclpp.git"
MSCCLPP_TAG="${MSCCLPP_TAG:-v0.8.0}"  # Pin a release; override with --tag
BUILDDIR="${BUILDDIR:-${PWD}/third-party/mscclpp}"
INSTALL_PREFIX="${MSCCLPP_HOME:-${BUILDDIR}/install}"
CLEAN_BUILD=0
USE_ROCM=0
JOBS="$(nproc)"

# --- Parse args ---
while [[ $# -gt 0 ]]; do
  case $1 in
    --rocm)       USE_ROCM=1;      shift ;;
    --clean)      CLEAN_BUILD=1;   shift ;;
    --tag)        MSCCLPP_TAG="$2"; shift 2 ;;
    --jobs|-j)    JOBS="$2";        shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--rocm] [--clean] [--tag <git-tag>] [--jobs N]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

echo "=== MSCCL++ build ==="
echo "  Tag:            ${MSCCLPP_TAG}"
echo "  Build dir:      ${BUILDDIR}"
echo "  Install prefix: ${INSTALL_PREFIX}"
echo "  ROCm:           ${USE_ROCM}"
echo "  Jobs:           ${JOBS}"
echo ""

# --- Clean ---
if [[ "${CLEAN_BUILD}" == "1" ]]; then
  echo "Cleaning previous build..."
  rm -rf "${BUILDDIR}"
fi

mkdir -p "${BUILDDIR}"

# --- Load MPI (required by MSCCL++ build) ---
if command -v ml &>/dev/null; then
  ml load mpi/hpcx-pmix-2.18 2>/dev/null || true
fi

# --- Clone ---
SRC_DIR="${BUILDDIR}/src"
if [[ ! -d "${SRC_DIR}" ]]; then
  echo "Cloning MSCCL++ (${MSCCLPP_TAG})..."
  git clone --depth 1 -b "${MSCCLPP_TAG}" "${MSCCLPP_REPO}" "${SRC_DIR}"
else
  echo "Source already present at ${SRC_DIR}, skipping clone."
  echo "  (Use --clean to force a fresh clone)"
fi

# --- Build ---
BUILD_OUT="${BUILDDIR}/build"
mkdir -p "${BUILD_OUT}"
cd "${BUILD_OUT}"

CMAKE_ARGS=(
  -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}"
  -DCMAKE_BUILD_TYPE=Release
  -DMSCCLPP_BUILD_TESTS=OFF
  -DBUILD_PYTHON_BINDINGS=OFF
)

if [[ "${USE_ROCM}" == "1" ]]; then
  # ROCm build
  ROCM_HOME="${ROCM_HOME:-/opt/rocm}"
  echo "Building for ROCm (ROCM_HOME=${ROCM_HOME})..."
  CMAKE_ARGS+=(
    -DMSCCLPP_USE_ROCM=ON
    -DCMAKE_PREFIX_PATH="${ROCM_HOME}"
  )
else
  # CUDA build
  CUDA_HOME="${CUDA_HOME:-/usr/local/cuda}"
  echo "Building for CUDA (CUDA_HOME=${CUDA_HOME})..."
  CMAKE_ARGS+=(
    -DCUDA_TOOLKIT_ROOT_DIR="${CUDA_HOME}"
  )
fi

cmake "${CMAKE_ARGS[@]}" "${SRC_DIR}"
make -j"${JOBS}"
make install

# --- Install Python package (needed for plan generation DSL) ---
# The mscclpp Python package includes the language DSL used to generate
# executor plans at test time (mscclpp.language.collectives, etc.).
# We only need the pure-Python DSL modules, not the compiled C extensions
# (which would install a second copy of libmscclpp.so that conflicts with
# the one we just built). The simplest approach: add the source tree's
# python/ directory to PYTHONPATH so `from mscclpp.language import ...` works.
echo ""
echo "Installing MSCCL++ Python package (plan generation DSL)..."
MSCCLPP_PYTHON_DIR="${SRC_DIR}/python"
if [[ -d "${MSCCLPP_PYTHON_DIR}/mscclpp/language" ]]; then
  # Create a .pth file in site-packages so Python finds the DSL modules
  SITE_PACKAGES="$(python3 -c 'import site; print(site.getsitepackages()[0])')"
  echo "${MSCCLPP_PYTHON_DIR}" > "${SITE_PACKAGES}/mscclpp-dsl.pth"
  echo "  Added ${MSCCLPP_PYTHON_DIR} to Python path via mscclpp-dsl.pth"

  # Create a _version.py stub (normally generated by setuptools-scm during
  # pip install, but we skip pip install to avoid building a second copy of
  # libmscclpp.so).
  if [[ ! -f "${MSCCLPP_PYTHON_DIR}/mscclpp/_version.py" ]]; then
    echo "__version__ = \"${MSCCLPP_TAG#v}\"" > "${MSCCLPP_PYTHON_DIR}/mscclpp/_version.py"
    echo "__commit_id__ = \"${MSCCLPP_TAG}\"" >> "${MSCCLPP_PYTHON_DIR}/mscclpp/_version.py"
    echo "  Created _version.py stub (version=${MSCCLPP_TAG#v})"
  fi
else
  echo "  WARNING: mscclpp.language DSL not found in ${MSCCLPP_PYTHON_DIR}"
  echo "  Plan generation at test time will not work."
fi

echo ""
echo "=== MSCCL++ installed to: ${INSTALL_PREFIX} ==="
echo ""
echo "To use with torchcomms:"
echo "  export MSCCLPP_HOME=${INSTALL_PREFIX}"
echo "  USE_MSCCLPP=ON pip install --no-build-isolation -v ."
